[package]
name    = "cargo-semver"
version = "1.0.2"
edition = "2021"

[dependencies]
clap      = { version = "4.5.4", features = ["derive"] }
eyre      = { version = "0.6.12" }
toml_edit = { version = "0.22.13" }
